name: Javadoc

on:
  push:
    branches: [ "main", "dev" ]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java & Gradle
        uses: ./.github/actions/set-java
        with:
          java-version: '11'

      - name: Run All Checks (Spotless, Checkstyle, Test)
        run: ./gradlew check

      - name: Generate Javadoc
        run: ./gradlew javadoc

      - name: Determine Target Branch
        id: set-branch
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "TARGET_BRANCH=pages" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "TARGET_BRANCH=dev-pages" >> $GITHUB_ENV
          fi

      - name: Push Javadoc to Target Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc
          publish_branch: ${{ env.TARGET_BRANCH }}
          keep_files: true
