# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      GH_ACTOR: ${{ github.actor }}
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep -E "^projectVersion=" gradle.properties | cut -d "=" -f 2)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Check if Release exists
        id: check_release
        run: |
          if gh release view v${{ env.VERSION }} -R ${{ github.repository }} >/dev/null 2>&1; then
            echo "Release v${{ env.VERSION }} already exists. Exiting gracefully."
            exit 0
          fi

      - name: Create Release
        run: gh release create v${{ env.VERSION }} --generate-notes

      - name: Build and Publish with Gradle
        run: ./gradlew publish

      - name: Upload to Release
        run: gh release upload v${{ env.VERSION }} build/libs/queqiao-tool-${{ env.VERSION }}.jar --clobber
