# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ github.token }}
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 8 for Shared Runner
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Make Gradle Wrapper executable
        run: chmod +x ./gradlew

      - name: Get Version
        id: get_version
        run: |
          VERSION=$(grep -E "^projectVersion=" gradle.properties | cut -d "=" -f 2)
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Handle existing Release
        run: |
          RELEASE_EXISTS=$(gh release view v${{ env.VERSION }} -R ${{ github.repository }} 2>&1 || true)
          if echo "$RELEASE_EXISTS" | grep -q "Not Found"; then
            echo "Release v${{ env.VERSION }} does not exist. Proceeding to create."
          else
            echo "Release v${{ env.VERSION }} exists. Deleting existing release."
            gh release delete v${{ env.VERSION }} -R ${{ github.repository }} -y --cleanup-tag || echo "Failed to delete release. It might not exist or there might be another issue."
          fi
          gh release create v${{ env.VERSION }} --generate-notes

      - name: Build and Publish with Gradle
        run: ./gradlew build publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        run: gh release upload v${{ env.VERSION }} target/queqiao-tool-${{ env.VERSION }}.jar --clobber
