name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java & Gradle
        uses: ./.github/actions/set-java
        with:
          java-version: '17'

      - name: Run Check
        run: ./gradlew check
      
      - name: Run Compile
        run: ./gradlew compileJava

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/reports/jacoco/test/jacocoTestReport.xml
