name: Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Java & Gradle
        uses: ./.github/actions/set-java
        with:
          java-version: '8'

      - name: Run All Checks
        run: ./gradlew check
